package com.FranGarcia.NuevaVersionGuardias.enums;

public enum Asignatura {
    // Asignaturas de Educación Secundaria Obligatoria (ESO)
    LENGUA_CASTELLANA_Y_LITERATURA,
    MATEMATICAS,
    CIENCIAS_SOCIALES,
    GEOGRAFIA_E_HISTORIA,
    CIENCIAS_NATURALES,
    BIOLOGIA_Y_GEOLOGIA,
    FISICA_Y_QUIMICA,
    EDUCACION_FISICA,
    EDUCACION_PLASTICA_Y_VISUAL,
    MUSICA,
    TECNOLOGIA,
    RELIGION,
    VALORES_ETICOS,

    // Asignaturas de Bachillerato
    FILOSOFIA,
    HISTORIA_DE_ESPANA,
    LENGUA_EXTRANJERA_INGLES,
    MATEMATICAS_I,
    MATEMATICAS_II,
    FISICA,
    QUIMICA,
    BIOLOGIA,
    GEOLOGIA,
    DIBUJO_TECNICO,
    ECONOMIA,
    LITERATURA_UNIVERSAL,
    HISTORIA_DEL_ARTE,

    // Asignaturas de Ciclos Formativos de Grado Básico
    OFIMATICA_Y_ARCHIVO_DE_DOCUMENTOS,
    INSTALACION_Y_MANTENIMIENTO_DE_RED_DATOS,
    MONTAJE_Y_MANTENIMIENTO_DE_SISTEMAS,
    OPERACIONES_AUXILIARES_DE_CONFIGURACION,
    APLICACIONES_BASICAS_DE_OFIMATICA,
    ATENCION_AL_CLIENTE,

    // Asignaturas de Ciclos Formativos de Grado Medio: Guía en el Medio Natural y Tiempo Libre
    TECNICAS_DE_EQUITACION,
    GUIA_ECUESTRE,
    ATENCION_A_GRUPOS,
    ORGANIZACION_DE_ITINERARIOS,
    GUIA_BAJA_Y_MEDIA_MONTANA,
    GUIA_DE_BICICLETA,
    SOCORRISMO_EN_EL_MEDIO_NATURAL,

    // Asignaturas de Ciclos Formativos de Grado Medio: Sistemas Microinformáticos y Redes
    MONTAJE_Y_MANTENIMIENTO_DE_EQUIPOS,
    SISTEMAS_OPERATIVOS_MONOPUESTO,
    APLICACIONES_OFIMATICAS,
    REDES_LOCALES,
    SISTEMAS_OPERATIVOS_EN_RED,
    SEGURIDAD_INFORMATICA,
    SERVICIOS_EN_RED,

    // Asignaturas de Ciclos Formativos de Grado Superior: Mecatrónica Industrial
    SISTEMAS_MECANICOS,
    SISTEMAS_HIDRAULICOS_Y_NEUMATICOS,
    SISTEMAS_ELECTRICOS_Y_ELECTRONICOS,
    ELEMENTOS_DE_MAQUINAS,
    PROCESOS_DE_FABRICACION,
    INTEGRACION_DE_SISTEMAS_DE_AUTOMATIZACION_INDUSTRIAL,

    // Asignaturas de Ciclos Formativos de Grado Superior: Desarrollo de Aplicaciones Multiplataforma
    SISTEMAS_INFORMATICOS,
    BASES_DE_DATOS,
    PROGRAMACION,
    LENGUAJES_DE_MARCAS_Y_SISTEMAS_DE_GESTION_DE_INFORMACION,
    ENTORNOS_DE_DESARROLLO,
    DESARROLLO_DE_INTERFACES,
    PROGRAMACION_MULTIMEDIA_Y_DISPOSITIVOS_MOVILES,

    // Asignaturas de Ciclos Formativos de Grado Superior: Desarrollo de Aplicaciones Web
    DESARROLLO_WEB_EN_ENTORNO_CLIENTE,
    DESARROLLO_WEB_EN_ENTORNO_SERVIDOR,

    // Curso de Especialización: Diseño de Videojuegos y Realidad Virtual
    DISENO_DE_VIDEOJUEGOS,
    PROGRAMACION_DE_VIDEOJUEGOS,
    MODELADO_Y_ANIMACION_3D,
    REALIDAD_VIRTUAL_Y_AUMENTADA,
    INTERACCION_Y_USABILIDAD;
}

